### ISSUE TITLE
Mode Filter

### ISSUE THREAD

**Issue by prono69** [EchterAlsFake/xnxx_api#2]
Hi, you did a great job and this is the most nice api I used . But there's a thing is still missing, is it possible to add a `mode` filter, like shown in ss ?
![Screenshot_20240830-100915434~01.jpg](https://github.com/user-attachments/assets/b9ccffec-c30d-472e-b201-07bc0f81cc97)

This will add `/hits` and `/random` parameter to the url.

**Comment by prono69** [comment]
This should be optional like any other `search_filter` by default, it sets to `default`

**Comment by EchterAlsFake** [comment]
Sure I'll add it.

**Comment by EchterAlsFake** [comment]
Should be done with v.1.4.2

**Comment by prono69** [comment]
Thank you so much
